### ISSUE TITLE
Cache strategy for .eslintcache

### ISSUE THREAD

**Issue by ibramsterdam** [juliusmarminge/good-defaults#1]
Hi! I really like your repo and I intend to use it. In one of your jobs you cache pnpm for performance which I like! 
In your eslint script you use the --cache flag so I guess it is your intention to generate a .eslintcache file to speed up your ci. However, every time you run your job you spin up a new ubuntu runner which does not have a .eslintcache file, and that makes your --cache flag basically useless.

So you can have two options: 1. You could persist the .eslintcache file to the github caching layer or 2. you could remove it.

If you intend to do the first one I would really like you to share this information with me because I got stuck on it in my own project's ci >.<. (and thats why I made this ticket, maybe helping you will be helping myself). 

I implemented this step:

```yml
      - name: "Cache .eslintcache"
        id: cache-eslint
        uses: actions/cache@v3
        env:
          cache-name: cache-eslintcache
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: pnpm lint
```

Only to find out that it successfully stores and fetches the .eslintcache but without any performance improvements.

When I would run:
```yml
   - run: pnpm lint
    - run: pnpm lint
 ```

I did clearly see an improvement of -40 seconds (which basically proves that the first .eslintcache file that I fetched is of no use...

I hope this feedback is usefull, I look forward to what you decide on and If you are able to implement the .eslintcache file your ci!
      

Greatings Bram
